### ISSUE TITLE
Improve condition on which default number of replicas are used

### ISSUE THREAD

**Issue by sbose78** [pedjak/rhthp-status-service-operator#1]
https://github.com/pedjak/rhthp-status-service-operator/blob/42f78d09473dcf948e53adae7f75924ce623673e/pkg/apis/app/v1alpha1/statusservice_types.go#L69

Hi,

I see a few issues with this approach:

- A user may intentionally set it to zero to imply deploy but keep it scaled to zero.
- If a positive value is what the number of replicas in a deployment should always be, how are we handling a scenario where a user sets replicas = -2

What are your thoughts?

**Comment by pedjak** [comment]
I would declare `Replicas` as positive number in openapi schema:

```
replicas:
              description: The desired number of service replicas
              format: int32
              type: integer
              minimum: 1
```

with that k8s checks if the resource is valid and responds with an error if not. I would not allow an user to deploy the services with zero replicas, if there is no strong use case against such behavior. 

PR #7 fixes the issues.
